const diagOptions = [
  'Accommodative Dysfunction',
  'Amblyopia',
  'Astigmatism',
  'Blepharitis',
  'Cataract',
  'Traumatic Mydriasis',
  'Skin Carcinoma',
  'Benign Lesion',
  'Melanoma',
  'Choroidal Nevus',
  'Nevus',
  'Retinal Lesion of Unknown Etiology',
  'Chalazion',
  'Color Vision Deficiency',
  'Computer Vision Syndrome',
  'Conjunctivitis (Viral)',
  'Conjunctivitis (Bacterial)',
  'Conjunctivitis (Allergic)',
  'Convergence Insufficiency',
  'Corneal Abrasion',
  'Corneal Ulcer',
  'Corneal Ulcer (Fungal)',
  'Corneal Ulcer (Bacterial)',
  'Mild Non-Proliferative Diabetic Retinopathy',
  'Moderate Non-Proliferative Diabetic Retinopathy',
  'Severe Non-Proliferative Diabetic Retinopathy',
  'Very Severe Non-Proliferative Diabetic Retinopathy',
  'Proliferative Diabetic Retinopathy',
  'Dry Eye',
  'Floaters',
  'Glaucoma Suspect',
  'Mild Primary Open Angle Glaucoma',
  'Moderate Primary Open Angle Glaucoma',
  'Severe Primary Open Angle Glaucoma',
  'Anatomically Narrow Angles',
  'Chronic Angle Closure Glaucoma',
  'Acute Angle Closure Glaucoma',
  'Photopsia of Unknown Etiology',
  'Hordeolum',
  'Hyperopia',
  'Keratitis',
  'Keratoconus',
  'Learning-related Vision Problems',
  'Macular Degeneration (Dry Form)',
  'Macular Degeneration (Wet Form)',
  'Migraine with Aura',
  'Myokymia',
  'Myopia',
  'Nystagmus',
  'Ocular Allergies',
  'Ocular Hypertension',
  'Ocular Migraine',
  'Pinguecula',
  'Presbyopia',
  'Pterygium',
  'Ptosis',
  'Retinal Detachment (Macula On)',
  'Retinal Detachment (Macula Off)',
  'Retinitis Pigmentosa',
  'Retinoblastoma',
  'Strabismus',
  'Subconjunctival Hemorrhage',
  'Vitreous Hemorrhage',
  'Retinal break or tear',
  'Subarachnoid Hemorrhage',
  'Intracranial Aneurysm',
  'Intracranial Mass/Tumor',
  'Cerebrovascular Event',
  'Optic Glioma',
  'Physiologic Cupping of the Optic Disc',
  'Posterior Vitreous Detachment',
  'Uveitis',
]

export const groupedDiagnosisOptions = [
  {
    "label": "Diagnosis Options",
    "options": diagOptions.map(option => ({ "value": option, "label": option }))
  }
]
